ERROR - 2024-08-28 23:48:38 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#4 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Commands\Database\CreateDatabase.php(136): CodeIgniter\Database\Config::forge()
#5 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\CreateDatabase->run(Array)
#6 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:create', Array)
#7 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Boot.php(351): CodeIgniter\CLI\Console->run()
#8 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp2\htdocs\os\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#3 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Commands\Database\CreateDatabase.php(136): CodeIgniter\Database\Config::forge()
#4 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\CreateDatabase->run(Array)
#5 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:create', Array)
#6 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Boot.php(351): CodeIgniter\CLI\Console->run()
#7 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#8 C:\xampp2\htdocs\os\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#9 {main}
ERROR - 2024-08-28 23:51:43 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#4 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Commands\Database\CreateDatabase.php(136): CodeIgniter\Database\Config::forge()
#5 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\CreateDatabase->run(Array)
#6 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:create', Array)
#7 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Boot.php(351): CodeIgniter\CLI\Console->run()
#8 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp2\htdocs\os\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#3 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Commands\Database\CreateDatabase.php(136): CodeIgniter\Database\Config::forge()
#4 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\CreateDatabase->run(Array)
#5 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:create', Array)
#6 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Boot.php(351): CodeIgniter\CLI\Console->run()
#7 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#8 C:\xampp2\htdocs\os\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#9 {main}
ERROR - 2024-08-28 23:52:09 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#4 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Commands\Database\CreateDatabase.php(136): CodeIgniter\Database\Config::forge()
#5 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\CreateDatabase->run(Array)
#6 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:create', Array)
#7 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Boot.php(351): CodeIgniter\CLI\Console->run()
#8 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp2\htdocs\os\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#3 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Commands\Database\CreateDatabase.php(136): CodeIgniter\Database\Config::forge()
#4 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\CreateDatabase->run(Array)
#5 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:create', Array)
#6 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Boot.php(351): CodeIgniter\CLI\Console->run()
#7 C:\xampp2\htdocs\os\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#8 C:\xampp2\htdocs\os\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#9 {main}
